"""Add income tracking tables and monthly view

Revision ID: 1f8eb3dfc59a
Revises: 02f7aa9ee333
Create Date: 2025-06-24 22:55:13.451184

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f8eb3dfc59a"
down_revision: Union[str, None] = "02f7aa9ee333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create income_sources table in tallyup schema
    op.execute("CREATE SCHEMA IF NOT EXISTS tallyup")

    # Use the existing currency type
    # The type is already created in a previous migration

    # Create income_sources table
    op.create_table(
        "income_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["tallyup.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="tallyup",
    )

    # Create incomes table
    op.create_table(
        "incomes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                name="currency",
                native_enum=False,
                create_constraint=False,
                validate_strings=True,
            ),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["tallyup.income_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tallyup",
    )

    # Create indexes for better query performance
    op.create_index(
        op.f("ix_tallyup_incomes_date"),
        "incomes",
        ["date"],
        unique=False,
        schema="tallyup",
    )
    op.create_index(
        op.f("ix_tallyup_income_sources_user_id"),
        "income_sources",
        ["user_id"],
        unique=False,
        schema="tallyup",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tallyup_income_sources_user_id"),
        table_name="income_sources",
        schema="tallyup",
    )
    op.drop_index(
        op.f("ix_tallyup_incomes_date"), table_name="incomes", schema="tallyup"
    )
    op.drop_table("incomes", schema="tallyup")
    op.drop_table("income_sources", schema="tallyup")
    # Note: We're not dropping the currency type as it might be used by other tables
    # ### end Alembic commands ###
