"""Add group table and user relation

Revision ID: 3436fb7b6efd
Revises: ce53eaafe1d3
Create Date: 2025-02-22 18:31:20.659180

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3436fb7b6efd"
down_revision: Union[str, None] = "ce53eaafe1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            server_onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="expense_tracker",
    )

    op.create_table(
        "users_groups",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["expense_tracker.users.id"], name="fk_users_groups_user_id"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["expense_tracker.groups.id"], name="fk_users_groups_group_id"
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
        schema="expense_tracker",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_groups", schema="expense_tracker")
    op.drop_table("groups", schema="expense_tracker")
    # ### end Alembic commands ###
