"""Init tables

Revision ID: 45e6e7766865
Revises:
Create Date: 2025-02-22 18:10:01.192368

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45e6e7766865"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create schema
    op.execute("CREATE SCHEMA IF NOT EXISTS expense_tracker")

    op.create_table(
        "expenses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="expense_tracker",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="expense_tracker",
    )
    op.create_table(
        "monthly_expenses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("expense_id", sa.String(), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expense_tracker.expenses.id"],  # Add schema qualification here
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="expense_tracker",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monthly_expenses", schema="expense_tracker")
    op.drop_table("users", schema="expense_tracker")
    op.drop_table("expenses", schema="expense_tracker")
    # Drop the enum type after dropping the table that uses it
    op.execute("DROP TYPE IF EXISTS expense_tracker.expense_category")
    op.execute("DROP SCHEMA IF EXISTS expense_tracker")
    # ### end Alembic commands ###
