"""simplify database structure and remove monthly_expenses table

Revision ID: 4fa1f283c0bb
Revises: 195da05e9c86
Create Date: 2025-04-24 17:00:13.722458

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fa1f283c0bb"
down_revision: Union[str, None] = "195da05e9c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tallyup")
    op.create_table(
        "groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tallyup",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="tallyup",
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("USD", "CLP", "EUR", name="currency", schema="tallyup"),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["tallyup.groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["tallyup.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tallyup",
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["tallyup.groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["tallyup.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
        schema="tallyup",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_groups", schema="tallyup")
    op.drop_table("expenses", schema="tallyup")
    op.drop_table("users", schema="tallyup")
    op.drop_table("groups", schema="tallyup")
    op.execute("DROP SCHEMA tallyup CASCADE")
    # ### end Alembic commands ###
