"""Tables should generate created at and updated at

Revision ID: ce53eaafe1d3
Revises: 45e6e7766865
Create Date: 2025-02-22 18:15:23.142264

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = "ce53eaafe1d3"
down_revision: Union[str, None] = "45e6e7766865"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify expenses table
    op.alter_column(
        "expenses",
        "created_at",
        type_=sa.DateTime(timezone=True),
        server_default=func.now(),
        existing_nullable=False,
        schema="expense_tracker",
    )
    op.alter_column(
        "expenses",
        "updated_at",
        type_=sa.DateTime(timezone=True),
        server_default=func.now(),
        server_onupdate=func.now(),
        existing_nullable=False,
        schema="expense_tracker",
    )

    # Modify users table
    op.alter_column(
        "users",
        "created_at",
        type_=sa.DateTime(timezone=True),
        server_default=func.now(),
        existing_nullable=False,
        schema="expense_tracker",
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            server_onupdate=func.now(),
            nullable=False,
        ),
        schema="expense_tracker",
    )

    # Modify monthly_expenses table
    op.add_column(
        "monthly_expenses",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            nullable=False,
        ),
        schema="expense_tracker",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from monthly_expenses
    op.drop_column("monthly_expenses", "created_at", schema="expense_tracker")

    # Remove updated_at from users
    op.drop_column("users", "updated_at", schema="expense_tracker")

    # Revert timestamp columns to regular DateTime
    op.alter_column(
        "users",
        "created_at",
        type_=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
        schema="expense_tracker",
    )
    op.alter_column(
        "expenses",
        "updated_at",
        type_=sa.DateTime(),
        server_default=None,
        server_onupdate=None,
        existing_nullable=False,
        schema="expense_tracker",
    )
    op.alter_column(
        "expenses",
        "created_at",
        type_=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
        schema="expense_tracker",
    )
    # ### end Alembic commands ###
